development:
  adapter: postgresql
  database: tic_tac_toe_test
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: tic_tac_toe_test
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
